std = "lua51"
max_line_length = false
exclude_files = {
    "libs/",
    ".luacheckrc"
}

ignore = {
    "211", -- Unused local variable
    "212", -- Unused argument
    "213", -- Unused loop variable
    "311", -- Value assigned to a local variable is unused
    "542", -- empty if branch
}

globals = {
    "SlashCmdList",
    "StaticPopupDialogs",
    "UpdateContainerFrameAnchors",
}

read_globals = {
    "bit",
    "ceil", "floor",
    "mod",
    "max",
    "table", "tinsert", "wipe", "copy",
    "string", "tostringall", "strtrim", "strmatch",

    -- our own globals

    -- misc custom, third party libraries
    "LibStub", "tekDebug",
    "GetAuctionBuyout",

    -- API functions
    "hooksecurefunc",
    "BankButtonIDToInvSlotID",
    "ContainerIDToInventoryID",
    "ReagentBankButtonIDToInvSlotID",
    "CursorHasItem",
    "DeleteCursorItem",
    "GetAddOnMetadata",
    "GetAuctionItemSubClasses",
    "GetBuildInfo",
    "GetBackpackAutosortDisabled",
    "GetBagSlotFlag",
    "GetBankAutosortDisabled",
    "GetBankBagSlotFlag",
    "GetContainerNumFreeSlots",
    "GetContainerNumSlots",
    "GetContainerItemID",
    "GetContainerItemInfo",
    "GetContainerItemLink",
    "GetCurrentGuildBankTab",
    "GetCursorInfo",
    "GetDetailedItemLevelInfo",
    "GetGuildBankItemInfo",
    "GetGuildBankItemLink",
    "GetGuildBankTabInfo",
    "GetGuildBankNumSlots",
    "GetInventoryItemID",
    "GetInventoryItemLink",
    "GetInventoryItemQuality",
    "GetItemClassInfo",
    "GetItemFamily",
    "GetItemInfo",
    "GetItemInfoInstant",
    "GetItemQualityColor",
    "GetTime",
    "InCombatLockdown",
    "IsAddOnLoaded",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsShiftKeyDown",
    "IsReagentBankUnlocked",
    "Item",
    "PickupContainerItem",
    "PickupGuildBankItem",
    "QueryGuildBankTab",
    "SplitContainerItem",
    "SplitGuildBankItem",
    "UnitIsAFK",
    "UnitLevel",
    "UnitName",
    "UseContainerItem",

    -- FrameXML frames
    "BankFrame",
    "InspectFrame",
    "MerchantFrame",
    "GameTooltip",
    "UIParent",
    "WorldFrame",
    "DEFAULT_CHAT_FRAME",
    "GameFontHighlightSmall",
    "NumberFontNormal",

    -- FrameXML API
    "EasyMenu",
    "Enum",
    "CloseDropDownMenus",
    "CreateFrame",
    "InterfaceOptionsFrame_OpenToCategory",
    "ToggleDropDownMenu",
    "UIDropDownMenu_AddButton",
    "UISpecialFrames",
    "ScrollingEdit_OnCursorChanged",
    "ScrollingEdit_OnUpdate",
    "InspectPaperDollFrame_OnShow",

    -- FrameXML Constants
    "ACHIEVEMENTS",
    "ACTION_PARTY_KILL",
    "ADD",
    "ALL",
    "ALT_KEY_TEXT",
    "ARTIFACT_POWER",
    "BACKPACK_CONTAINER",
    "BACKPACK_TOOLTIP",
    "BAG_CLEANUP_BAGS",
    "BAG_FILTER_EQUIPMENT",
    "BAG_FILTER_ICONS",
    "BAGSLOT",
    "BANK",
    "BANK_BAG_PURCHASE",
    "BANK_CONTAINER",
    "CHAT_MSG_SAY",
    "CHAT_MSG_YELL",
    "CHAT_MSG_PARTY",
    "CHAT_MSG_RAID",
    "CHAT_MSG_GUILD",
    "CHAT_MSG_OFFICER",
    "CLASS_ICON_TCOORDS",
    "CLICK_FOR_DETAILS",
    "CLOSE",
    "COLOR",
    "COMMUNITIES_DEFAULT_CHANNEL_NAME",
    "COMPLETE",
    "CONFIRM_BUY_BANK_SLOT",
    "COVENANT_COLORS",
    "CTRL_KEY_TEXT",
    "DEFAULT",
    "DRAG_MODEL",
    "ENABLE",
    "ENCOUNTER_JOURNAL_ITEM",
    "EQUIP_CONTAINER",
    "GREEN_FONT_COLOR",
    "HIDE",
    "ICON_LIST",
    "ID",
    "IGNORE",
    "INCOMPLETE",
    "ITEM_BIND_ON_EQUIP",
    "ITEM_BIND_ON_PICKUP",
    "ITEM_BIND_ON_USE",
    "ITEM_BIND_QUEST",
    "ITEM_BIND_TO_BNETACCOUNT",
    "ITEM_BNETACCOUNTBOUND",
    "ITEM_CONJURED",
    "ITEM_PET_KNOWN",
    "ITEM_QUALITY_COLORS",
    "ITEM_REQ_SKILL",
    "ITEM_SET_NAME",
    "ITEM_SOULBOUND",
    "ITEM_UNIQUE",
    "LE_BAG_FILTER_FLAG_EQUIPMENT",
    "LE_BAG_FILTER_FLAG_IGNORE_CLEANUP",
    "LE_ITEM_CLASS_WEAPON",
    "LE_ITEM_CLASS_ARMOR",
    "LE_ITEM_CLASS_CONTAINER",
    "LE_ITEM_CLASS_GEM",
    "LE_ITEM_CLASS_ITEM_ENHANCEMENT",
    "LE_ITEM_CLASS_CONSUMABLE",
    "LE_ITEM_CLASS_GLYPH",
    "LE_ITEM_CLASS_TRADEGOODS",
    "LE_ITEM_CLASS_RECIPE",
    "LE_ITEM_CLASS_BATTLEPET",
    "LE_ITEM_CLASS_QUESTITEM",
    "LE_ITEM_CLASS_MISCELLANEOUS",
    "LE_ITEM_QUALITY_POOR",
    "LE_PARTY_CATEGORY_HOME",
    "LE_PARTY_CATEGORY_INSTANCE",
    "LOCALIZED_CLASS_NAMES_FEMALE",
    "LOCALIZED_CLASS_NAMES_MALE",
    "LOCATION_COLON",
    "LOOT",
    "MAP_PIN",
    "MAP_PIN_HYPERLINK",
    "MAX_ACCOUNT_MACROS",
    "MAX_CONTAINER_ITEMS",
    "MOUNT",
    "MOVE_FRAME",
    "NEED",
    "NEVER",
    "NEW_ITEM_ATLAS_BY_QUALITY",
    "NO",
    "NONE",
    "NUM_BAG_SLOTS",
    "NUM_BANKBAGSLOTS",
    "NUM_CONTAINER_FRAMES",
    "NUM_LE_BAG_FILTER_FLAGS",
    "PARENS_TEMPLATE",
    "PREVIEW",
    "PROFESSIONS_USED_IN_COOKING",
    "QUESTS_COLON",
    "RAID_CLASS_COLORS",
    "REAGENT_BANK",
    "REAGENTBANK_CONTAINER",
    "REAGENTBANK_DEPOSIT",
    "RED_FONT_COLOR",
    "REMOVE",
    "SEARCH_LOADING_TEXT",
    "SHIFT_KEY_TEXT",
    "SOUNDKIT",
    "STATICPOPUP_NUMDIALOGS",
    "SUBTITLE_FORMAT",
    "TARGET",
    "TEXTURE_ITEM_QUEST_BANG",
    "TEXTURE_ITEM_QUEST_BORDER",
    "TEXTURES_SUBHEADER",
    "TOOLTIP_BATTLE_PET",
    "TOY",
    "TRADESKILL_POST",
    "UIDROPDOWNMENU_MENU_VALUE",
    "UI_SCALE",
    "UNKNOWN",
    "UNKNOWNOBJECT",
    "USED",
    "YES",
    "ZONE",
}
